### ISSUE TITLE
python error

### ISSUE THREAD

**Issue by qidizi** [kaio/ibus-table#53]
[qidizi@pc Downloads]$ ibus-daemon 
Traceback (most recent call last):
  File "/usr/share/ibus-table/engine/main.py", line 28, in <module>
    from gi import require_version
  File "/usr/lib/python3.4/site-packages/gi/__init__.py", line 39
    print url
            ^
SyntaxError: Missing parentheses in call to 'print'
^C

-------
print(url)

**Comment by mike-fabian** [comment]
I have no idea how to reproduce this. I have never seen anything like this.

I am closing this, unless you can give instructions on how to reproduce it using the latest version.
